### ISSUE TITLE
Add unpdate user profile function and page

### ISSUE THREAD

**Issue by BazingaOo** [BazingaOo/IMDB_Clone#37]

**Comment by wangyx98** [comment]
We, front-ends, need the updating port for user profile from back-ends.

**Comment by dtxpder** [comment]
use the address "this.$axios.post("/api/user/UpdateProfile", this.$qs.stringify(params))" for api request

**Comment by BazingaOo** [comment]
we already updated the api and we still need some user information like username, gender, age, etc. please add in the 'params'. If we can receive these parameters, this function will be done.
